[2025-07-27T10:17:08.801+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-27T10:17:09.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-04-03T00:00:00+00:00 map_index=1 [queued]>
[2025-07-27T10:17:09.454+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-04-03T00:00:00+00:00 map_index=1 [queued]>
[2025-07-27T10:17:09.468+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-27T10:17:09.713+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): add_one> on 2022-04-03 00:00:00+00:00
[2025-07-27T10:17:09.838+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2146) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-27T10:17:09.889+0000] {standard_task_runner.py:64} INFO - Started process 2277 to run task
[2025-07-27T10:17:09.847+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_dynamic_task_mapping', 'add_one', 'scheduled__2022-04-03T00:00:00+00:00', '--job-id', '221', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_dynamic_task_mapping.py', '--cfg-path', '/tmp/tmpbkc06ymo', '--map-index', '1']
[2025-07-27T10:17:09.939+0000] {standard_task_runner.py:91} INFO - Job 221: Subtask add_one
[2025-07-27T10:17:10.041+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T10:17:10.447+0000] {task_command.py:426} INFO - Running <TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-04-03T00:00:00+00:00 map_index=1 [running]> on host 4112a2618ff3
[2025-07-27T10:17:10.985+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-27T10:17:11.276+0000] {process_utils.py:132} INFO - Sending 15 to group 2277. PIDs of all processes in the group: [2277]
[2025-07-27T10:17:11.278+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2277
[2025-07-27T10:17:12.164+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2277, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='10:17:09') (2277) terminated with exit code -15
[2025-07-27T10:17:12.212+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 143
[2025-07-27T10:17:13.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
