[2025-07-29T07:57:04.831+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-29T07:57:09.071+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T07:53:35.889550+00:00 map_index=2 [queued]>
[2025-07-29T07:57:10.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T07:53:35.889550+00:00 map_index=2 [queued]>
[2025-07-29T07:57:10.620+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-29T07:57:19.031+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): scrape_task> on 2025-07-29 07:53:35.889550+00:00
[2025-07-29T07:57:19.091+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_scraping_pipeline', 'scrape_task', 'manual__2025-07-29T07:53:35.889550+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/parallel_pipeline_dag.py', '--cfg-path', '/tmp/tmpqv63sejl', '--map-index', '2']
[2025-07-29T07:57:19.091+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2841) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-29T07:57:19.095+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask scrape_task
[2025-07-29T07:57:19.096+0000] {standard_task_runner.py:64} INFO - Started process 2874 to run task
[2025-07-29T07:57:23.522+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-29T07:57:33.314+0000] {task_command.py:426} INFO - Running <TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T07:53:35.889550+00:00 map_index=2 [running]> on host 507e5441ba68
[2025-07-29T07:58:25.585+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 59 for task scrape_task ((psycopg2.OperationalError) SSL SYSCALL error: EOF detected

[SQL: SELECT task_instance.try_number, task_instance.task_display_name, task_instance.task_id, task_instance.dag_id, task_instance.run_id, task_instance.map_index, task_instance.start_date, task_instance.end_date, task_instance.duration, task_instance.state, task_instance.max_tries, task_instance.hostname, task_instance.unixname, task_instance.job_id, task_instance.pool, task_instance.pool_slots, task_instance.queue, task_instance.priority_weight, task_instance.operator, task_instance.custom_operator_name, task_instance.queued_dttm, task_instance.queued_by_job_id, task_instance.pid, task_instance.executor_config, task_instance.updated_at, task_instance.rendered_map_index, task_instance.external_executor_id, task_instance.trigger_id, task_instance.trigger_timeout, task_instance.next_method, task_instance.next_kwargs, dag_run_1.state AS state_1, dag_run_1.id, dag_run_1.dag_id AS dag_id_1, dag_run_1.queued_at, dag_run_1.execution_date, dag_run_1.start_date AS start_date_1, dag_run_1.end_date AS end_date_1, dag_run_1.run_id AS run_id_1, dag_run_1.creating_job_id, dag_run_1.external_trigger, dag_run_1.run_type, dag_run_1.conf, dag_run_1.data_interval_start, dag_run_1.data_interval_end, dag_run_1.last_scheduling_decision, dag_run_1.dag_hash, dag_run_1.log_template_id, dag_run_1.updated_at AS updated_at_1, dag_run_1.clear_number 
FROM task_instance JOIN dag_run AS dag_run_1 ON dag_run_1.dag_id = task_instance.dag_id AND dag_run_1.run_id = task_instance.run_id 
WHERE task_instance.dag_id = %(dag_id_2)s AND task_instance.run_id = %(run_id_2)s AND task_instance.task_id = %(task_id_1)s AND task_instance.map_index = %(map_index_1)s]
[parameters: {'dag_id_2': 'parallel_scraping_pipeline', 'run_id_2': 'manual__2025-07-29T07:49:10.770230+00:00', 'task_id_1': 'scrape_task', 'map_index_1': -1}]
(Background on this error at: https://sqlalche.me/e/14/e3q8); 2874)
[2025-07-29T07:58:59.808+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-29T07:59:18.309+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-29T07:59:25.612+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
